### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by d4rkm0nkey** [CottonMC/Jankson-Fabric#12]
The mod extra-pieces is a very important mod for me and as the owner doesn't want to update it, I am now trying to. Problem is that it depends on Jankson-Fabric and I can't find a version of Jankson-Fabric that works with 1.17.

It would help me a lot if Jankson-Fabric would be updated to 1.17, as I don't know how to replace it's code.

**Comment by Juuxel** [comment]
The 1.16 version should work on 1.17. You can also just use the [normal version of Jankson](https://github.com/falkreon/Jankson) from Maven Central if you don't need the Minecraft-specific serialisers.

**Comment by SFort** [comment]
can confirm this works on 1.17

@d4rkm0nkey 
if your fine with all the blocks having the pickaxe as the breaking tool
i lazily ported [extra-pieces](https://github.com/SFort/extra-pieces)

**Comment by d4rkm0nkey** [comment]
ok, thank you guys!
