### ISSUE TITLE
Display as Library in Mod Menu

### ISSUE THREAD

**Issue by MightyKnight** [CottonMC/Jankson-Fabric#17]
**Is your feature request related to a problem? Please describe.**
The mod appears in the normal Modmenu list, even if library mods are hidden.
Usually you would only want to see the userfacing mods and it might cause confusion, e.g. "I didn't install this".

**Describe the solution you'd like**
Modmenu provides a way to specify it in the fabric.mod.json:
```
"custom": {
  "modmenu": {
    "badges": [ "library" ]
  }
}
```

**Comment by falkreon** [comment]
Modmenu seems to have changed their API for this. The old way was
```json
"custom": {
    "modmenu:api": true
}
```

which jankson-fabric still does.

**Comment by Juuxel** [comment]
Yeah that was deprecated over a year ago and removed at some point
