### ISSUE TITLE
1.19.3 Support - copy of LibGUI bug report

### ISSUE THREAD

**Issue by mrmelon54** [CottonMC/Jankson-Fabric#18]
**Describe the bug**
I'm a fellow mod dev trying to update my mod to 1.19.3.
Here is a bug report: https://mclo.gs/dqG11ir

**To Reproduce**
1. Game just crashes on launch

**Version of the (please complete the following information):**
 - [Multiple Server Lists](https://modrinth.com/mod/multiple-server-lists) (dev 1.19.3 version) - my mod
 - LibGUI 6.3.0-1.19 as library
 - Fabric API 0.68.1+1.19.3
 - Minecraft 1.19.3

**Comment by mrmelon54** [comment]
I was told the log looks like a jankson-fabric bug so I'm reporting the issue here too:
LibGUI: https://github.com/CottonMC/LibGui/issues/178
Multiple Server Lists (my mod): https://github.com/MrMelon54/multiple-server-lists-fabric/issues/7

**Comment by falkreon** [comment]
Looks like something happened to the Activity class / Registry.ACTIVITY.

**Comment by Juuxel** [comment]
All the registry instances were moved to a new class, `Registries`. All of them need to be changed 😅

**Comment by mrmelon54** [comment]
Well thanks for the update :+1:

**Comment by Juuxel** [comment]
Fixed in 0adec54f03dd42e06214281d349b9090b0b05e84.
